# Generated by Django 4.2.3 on 2023-08-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_mystudies'),
    ]

    operations = [
        migrations.AddField(
            model_name='mystudies',
            name='logo',
            field=models.ImageField(null=True, upload_to='..\\static\\css'),
        ),
    ]
