# Generated by Django 4.2.3 on 2023-08-16 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_myprojects_user_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mystudies',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
