# Generated by Django 4.2.3 on 2023-08-16 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_mystudies_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mystudies',
            name='logo',
        ),
    ]
